# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d29e2da7bb8918d44ee297a635d6569854befa832b4d49041642e9e3df158ce6af2ced011520fceb4f043ba91ae9653feb5267d89e9f7cc56ed28398758b8958

test:
  secret_key_base: ffbe62c1dc18f413eed53a42805273d86c9de76bfb26cd9095107210e29bdcfff289d2e677a83df173ae9dd0bfcbd81599290feaf199860640102cb6d65df0ff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

 #   gmail_username: 'felipewebtechnologies@gmail.com'
  #  gmail_password: 'fionayfender1996'